### ISSUE TITLE
Creating album not working properly

### ISSUE THREAD

**Issue by miduku** [lossendae/Cliche#7] opened 2012-02-01 13:38 UTC
Using **2.2.0-pl2 (advanced)** and **Cliche 1.0.1 beta3**.

When I try to create an Album it won't apear in backend and it keeps showing me that its loading... but nothing happens. 

I think the album was created since I wanted to create another one with the same name and it told me that it already exists

**Comment by lossendae** [comment] 2012-02-01 15:56
It's a problem who arise when the original table is still populated and Cliche can't find the image(s). 
You need to truncate both cliche's table in your database.
This bug will be solved in the next release.
Thanks for your report :)

**Comment by skndn60** [comment] 2012-02-20 00:08
I have the same issue. Emptied both tables but to no avail. "Loading" spinner keeps turning...

Thanks for your help.

**Comment by lossendae** [comment] 2012-02-20 08:03
Can you check if you have a specific error message in your browser console ?

**Comment by skndn60** [comment] 2012-02-20 08:34
No specific error messages in the log. It just doesn't seem to get past the loading of the albums although the albums do get created as they appear in the DB table.

**Comment by lossendae** [comment] 2012-02-20 08:58
That's odd, any error in the modx error log ?

**Comment by skndn60** [comment] 2012-02-20 09:04
Nope, nothing there either. I uninstalled, removed, re-downloaded and re-installed but it will not do its thing...

**Comment by skndn60** [comment] 2012-02-20 09:08
Tried again. Install log shows:

Console running...
Attempting to install package with signature: cliche-1.0.1-beta3
Package found...now preparing to install.
Grabbing package workspace...
Workspace environment initiated, now installing package...
Could not load package metadata for package cliche.
Successfully installed package cliche-1.0.1-beta3

MODX error log shows:

[2012-02-20 09:06:19](ERROR @ /connectors/workspace/packages.php) MODX could not download the file. You must enable allow_url_fopen, cURL or fsockopen to use remote transport packaging.

**Comment by lossendae** [comment] 2012-02-20 18:28
What version of MODx are you using ?
Would you mind if i take a look at the install ?

**Comment by skndn60** [comment] 2012-02-20 21:01
MODX Revolution 2.2.0-pl2 (traditional).

It's a local install on my iMac running MAMP.

How would you want to "take a look"... ?

**Comment by lossendae** [comment] 2012-02-20 21:45
I guess I should have asked if it was viewable online :)

The message you had as nothing to do with the component but rather with the package manager to access the remote modx repository.

Do you have any message in your apache logs ?
What the returned response from the php script on the CMP, is it empty or a json object ?
If it's a json object, what does it contains ? 
Did you verify if the cliche assets directory contains a folder named albums with subdirectories of each album ids created in it ?

**Comment by skndn60** [comment] 2012-02-20 22:08
No, unfortunately it's a local install... :-)

There are some Cliche errors in the PHP log:

[19-Feb-2012 23:55:18] PHP Fatal error:  Call to a member function get() on a non-object in /Applications/MAMP/htdocs/core/components/cliche/processors/mgr/album/getlist.php on line 51

[19-Feb-2012 23:55:29] PHP Fatal error:  Call to a member function get() on a non-object in /Applications/MAMP/htdocs/core/components/cliche/processors/mgr/albums/getlist.php on line 36

[20-Feb-2012 00:10:02] PHP Fatal error:  Call to a member function toArray() on a non-object in /Applications/MAMP/htdocs/core/components/cliche/processors/mgr/album/getlist.php on line 48

Under /Applications/MAMP/htdocs/assets/components/cliche are NO subdirectories for albums. There are records in the album table and if I try to create the same album twice Cliche signals an error....

**Comment by lossendae** [comment] 2012-02-20 22:35
I think the problem is in the query, would you mind try an update tomorrow from the git repository (after i push some additionnal checks in the processors) ?

**Comment by skndn60** [comment] 2012-02-20 22:45
Sure! Just let me know when the update is there...

**Comment by lossendae** [comment] 2012-02-23 13:30
I have committed a working version. Can you test it and feedback ?

**Comment by skndn60** [comment] 2012-02-23 21:21
Good news! I downloaded the code from Git and replaced the code I got from MODX package management. Works great. Just out of curiosity, what was the problem?

& thanks for your help!

**Comment by lossendae** [comment] 2012-02-24 09:17
Probably close to miduku's issue, but the fix was already committed (Double checking on files/directory and initialization of empty variables for Extjs)
I'll have to release the current git version asap because the one on the repo is flawed.

Thanks for taking the time to test :)

**Comment by gadgetto** [comment] 2012-04-05 08:40
Downloaded Cliche today (2012-04-05) and too having the same problem as the initial poster.
Updated MODx Revo yesterday to 2.2.1-pl.
Cliche is at version 1.0.1-beta3 I think.

**Comment by fourroses666** [comment] 2012-04-15 23:00
MODX Revolution 2.2.0-pl2 (traditional)
Latest version 16 april 1012

Same error, after manual update files grabbed from github it works! 
https://github.com/lossendae/Cliche

I had some install problems/errors/failures so guess some files where missing.

Must say, it looks very very good! Thanks allot Lossendae for this package :)

**Closed as completed** 2012-04-19 13:57 UTC
